# Generated by Django 5.0 on 2023-12-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип тарифа',
                'verbose_name_plural': 'Типы тарифов',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtitle', models.CharField(max_length=255, verbose_name='Название')),
                ('speed', models.IntegerField(verbose_name='Скорость')),
                ('tv', models.IntegerField(verbose_name='Количество каналов')),
                ('desc', models.TextField(max_length=7000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена за месяц')),
                ('rtype', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.rtype', verbose_name='Тип тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
