# Generated by Django 5.0 on 2023-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rtype_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('ctype', models.CharField(max_length=255, verbose_name='Тип клиента')),
                ('text', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
